const makeEntry = (status, owner, workPackage, source = 'webBridge') => ({
  status,
  owner,
  workPackage,
  source,
});

module.exports = {
  version: 'wp-a-contract-manifest-v1',
  methods: {
    app: {
      getVersion: makeEntry('pending', 'web-shell', 'WP-G'),
      getGpuHardwareAccelerationStatus: makeEntry('pending', 'web-shell', 'WP-G'),
      saveGpuHardwareAccelerationPreference: makeEntry('pending', 'web-shell', 'WP-G'),
      startGpuHardwareAccelerationTrial: makeEntry('pending', 'web-shell', 'WP-G'),
      relaunchWithGpuHardwareAccelerationDisabled: makeEntry('pending', 'web-shell', 'WP-G'),
      getLatestVersion: makeEntry('pending', 'web-shell', 'WP-G'),
      getUpdateDownloadUrl: makeEntry('pending', 'web-shell', 'WP-G'),
      checkUpdate: makeEntry('pending', 'web-shell', 'WP-G'),
      startUpdate: makeEntry('pending', 'web-shell', 'WP-G'),
      quitAndInstall: makeEntry('pending', 'web-shell', 'WP-G'),
    },
    requiredOnlineServices: {
      getStatus: makeEntry('pending', 'runtime', 'WP-G'),
    },
    config: {
      load: makeEntry('implemented', 'settings', 'WP-A'),
      save: makeEntry('implemented', 'settings', 'WP-A'),
      listModels: makeEntry('pending', 'settings', 'WP-C'),
      openConfigFolder: makeEntry('pending', 'settings', 'WP-C'),
    },
    license: {
      getStatus: makeEntry('pending', 'settings', 'WP-G'),
      refresh: makeEntry('pending', 'settings', 'WP-G'),
      importOfflineFile: makeEntry('pending', 'settings', 'WP-G'),
      activateOfflineCode: makeEntry('pending', 'settings', 'WP-G'),
    },
    ai: {
      chat: makeEntry('pending', 'runtime', 'WP-C'),
      requestJson: makeEntry('pending', 'runtime', 'WP-C'),
      testImageModel: makeEntry('pending', 'runtime', 'WP-C'),
    },
    agent: {
      listRuntimes: makeEntry('pending', 'runtime', 'WP-E'),
      run: makeEntry('pending', 'runtime', 'WP-E'),
      selfCheck: makeEntry('pending', 'runtime', 'WP-E'),
      exportSelfCheckReport: makeEntry('pending', 'runtime', 'WP-E'),
      getStatus: makeEntry('pending', 'runtime', 'WP-E'),
      restart: makeEntry('pending', 'runtime', 'WP-E'),
    },
    developerTokenStats: {
      openWindow: makeEntry('pending', 'developer', 'WP-B'),
      get: makeEntry('pending', 'developer', 'WP-B'),
      reset: makeEntry('pending', 'developer', 'WP-B'),
    },
    developerExpansionReplaceTest: {
      run: makeEntry('pending', 'developer', 'WP-B'),
    },
    file: {
      selectDuplicateCheckFiles: makeEntry('pending', 'workflow', 'WP-D'),
    },
    knowledgeBase: {
      getMigrationStatus: makeEntry('implemented', 'knowledge', 'WP-A'),
      migrateLegacy: makeEntry('implemented', 'knowledge', 'WP-A'),
      list: makeEntry('pending', 'knowledge', 'WP-C'),
      createFolder: makeEntry('pending', 'knowledge', 'WP-C'),
      renameFolder: makeEntry('implemented', 'knowledge', 'WP-A'),
      reorderFolder: makeEntry('pending', 'knowledge', 'WP-C'),
      deleteFolder: makeEntry('implemented', 'knowledge', 'WP-A'),
      deleteDocument: makeEntry('implemented', 'knowledge', 'WP-A'),
      moveDocument: makeEntry('implemented', 'knowledge', 'WP-A'),
      uploadDocuments: makeEntry('pending', 'knowledge', 'WP-D'),
      retryDocument: makeEntry('implemented', 'knowledge', 'WP-A'),
      startMatching: makeEntry('pending', 'knowledge', 'WP-C'),
      readMarkdown: makeEntry('implemented', 'knowledge', 'WP-A'),
      readItems: makeEntry('implemented', 'knowledge', 'WP-A'),
      readAnalysis: makeEntry('implemented', 'knowledge', 'WP-A'),
    },
    technicalPlan: {
      loadState: makeEntry('implemented', 'technical-plan', 'WP-A'),
      importTenderDocument: makeEntry('pending', 'technical-plan', 'WP-D'),
      importOriginalPlanDocument: makeEntry('pending', 'technical-plan', 'WP-D'),
      checkBidSections: makeEntry('implemented', 'technical-plan', 'WP-A'),
      selectBidSection: makeEntry('implemented', 'technical-plan', 'WP-A'),
      readTenderMarkdown: makeEntry('implemented', 'technical-plan', 'WP-A'),
      readTenderSourceMarkdown: makeEntry('implemented', 'technical-plan', 'WP-A'),
      readOriginalPlanMarkdown: makeEntry('implemented', 'technical-plan', 'WP-A'),
      updateStep: makeEntry('implemented', 'technical-plan', 'WP-A'),
      setWorkflowKind: makeEntry('implemented', 'technical-plan', 'WP-A'),
      switchWorkflowKind: makeEntry('implemented', 'technical-plan', 'WP-A'),
      saveBidAnalysisConfig: makeEntry('implemented', 'technical-plan', 'WP-A'),
      saveOutlineConfig: makeEntry('implemented', 'technical-plan', 'WP-A'),
      saveOutline: makeEntry('implemented', 'technical-plan', 'WP-A'),
      saveGlobalFacts: makeEntry('implemented', 'technical-plan', 'WP-A'),
      saveContentGenerationOptions: makeEntry('implemented', 'technical-plan', 'WP-A'),
      saveChapterContent: makeEntry('implemented', 'technical-plan', 'WP-A'),
      clear: makeEntry('implemented', 'technical-plan', 'WP-A'),
    },
    duplicateCheck: {
      loadState: makeEntry('implemented', 'workflow', 'WP-A'),
      saveFiles: makeEntry('implemented', 'workflow', 'WP-A'),
      saveUiState: makeEntry('implemented', 'workflow', 'WP-A'),
      updateState: makeEntry('implemented', 'workflow', 'WP-A'),
      clear: makeEntry('implemented', 'workflow', 'WP-A'),
    },
    rejectionCheck: {
      loadState: makeEntry('implemented', 'workflow', 'WP-A'),
      importDocument: makeEntry('pending', 'workflow', 'WP-D'),
      importTenderFromTechnicalPlan: makeEntry('implemented', 'workflow', 'WP-A'),
      removeDocument: makeEntry('implemented', 'workflow', 'WP-A'),
      saveUiState: makeEntry('implemented', 'workflow', 'WP-A'),
      updateState: makeEntry('implemented', 'workflow', 'WP-A'),
      clear: makeEntry('implemented', 'workflow', 'WP-A'),
    },
    templates: {
      list: makeEntry('implemented', 'workflow', 'WP-A'),
      get: makeEntry('implemented', 'workflow', 'WP-A'),
      create: makeEntry('implemented', 'workflow', 'WP-A'),
      update: makeEntry('implemented', 'workflow', 'WP-A'),
      delete: makeEntry('implemented', 'workflow', 'WP-A'),
    },
    tasks: {
      startBidSectionExtraction: makeEntry('pending', 'workflow', 'WP-C'),
      startBidAnalysis: makeEntry('pending', 'workflow', 'WP-C'),
      startOutlineGeneration: makeEntry('pending', 'workflow', 'WP-C'),
      startGlobalFactsGeneration: makeEntry('pending', 'workflow', 'WP-C'),
      startContentGeneration: makeEntry('pending', 'workflow', 'WP-C'),
      pauseContentGeneration: makeEntry('pending', 'workflow', 'WP-C'),
      startRejectionItemsExtraction: makeEntry('pending', 'workflow', 'WP-C'),
      startRejectionCheck: makeEntry('pending', 'workflow', 'WP-C'),
      startDuplicateAnalysis: makeEntry('pending', 'workflow', 'WP-C'),
      getActiveTasks: makeEntry('implemented', 'workflow', 'WP-A'),
    },
    export: {
      exportWord: makeEntry('pending', 'export', 'WP-F'),
      openFile: makeEntry('pending', 'export', 'WP-F'),
    },
    systemFonts: {
      list: makeEntry('pending', 'web-shell', 'WP-F'),
    },
    resources: {
      list: makeEntry('removed', 'legacy', 'WP-A', 'deleted-product'),
    },
    tenderOpportunities: {
      list: makeEntry('removed', 'legacy', 'WP-A', 'deleted-product'),
    },
    plugins: {
      list: makeEntry('removed', 'legacy', 'WP-A', 'deleted-product'),
    },
  },
};
